name: Format images

on:
  pull_request:
    paths:
      - 'logoIcons/**/*.jpg'
      - 'logoIcons/**/*.jpeg'
      - 'logoIcons/**/*.png'
      - 'logoIcons/**/*.webp'

jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Get logo icons changed
        id: changed-logo-icons
        uses: tj-actions/changed-files@v37
        with:
          separator: ','
          files: |
            ./logoIcons

      - name: Resize images to 200x200 and convert to .png
        run: |
          IFS=$','
          vals="${{ steps.changed-logo-icons.outputs.all_changed_and_modified_files }}"
          for file in $vals; do
            npx sharp resize 200 200 --format png --output ./logoIcons --input "$file"
          done

      - name: Remove any left over none png images from sharp command
        run: cd ./logoIcons && find . -type f ! -name '*.png' -delete

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Delete non-PNG images and resize other images"
          git push

      - name: Compress images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
